spring:
  thymeleaf:
    prefix: classpath:/templates/

server:
  port: 56518
  servlet:
    context-path: "/"

websocket:
  path: /home/work/xxx.log
  local: true
  url: xxx
  username: xxx
  password: xxx
